#!/bin/bash

 ################################################
#  Workflow from sarek output to annovar output  #
# 1. only keep variants in cancer genes          #
# 2. perform QC using qc_filt script (high)      #
# 3. takes vcf input and generates avinput       #
# 4. annotates using databases in db_path        #
 ################################################

ml BCFtools

#getopts for handling arguments fluidly

vcf=""
mode=""

while getopts "hi:m:" optionName; do
    case "$optionName" in
        i)
            vcf="$OPTARG"
            if [[ ! "$vcf" =~ \.vcf$ && ! "$vcf" =~ \.vcf\.gz$ ]]; then
                echo "Error: Input VCF file must end with '.vcf' or '.vcf.gz'" >&2
                exit 1
            fi
            ;;
        m)
            mode="$OPTARG"
            if [[ ! "$mode" =~ ^[lhxs]$ ]]; then
                echo "Error: Mode must be one of 'l' (low qual), 'h' (high qual), 'x' (xtra high qual), or 's' (structural vars)" >&2
                exit 1
            fi
            ;;
        [?]) printErrorHelpAndExit "$badOptionHelp";;
    esac
done

#define annovar db path

db_path="/dss/work/doad5844/ext/annovar/humandb/"
echo "$db_path"

#Indexing
echo "indexing input"
bcftools index $vcf

#Filter by cancer genes
echo "filtering by cancer genes"
bcftools filter -R ~/cg_v2.bed -o cg_filt.vcf.gz $vcf

#QC
if [ ! -f "cg_filt.vcf.gz" ]; then
    echo "Error: cg_filt.vcf.gz not found in the current working directory."
    exit 1
fi

if [[ "$mode" == "l" ]]; then
    echo "QC (Mode : Low)"
    qc_filt -l cg_filt.vcf.gz
    annovar_in="lq.vcf.gz"
    name="lq"
elif [[ "$mode" == "h" ]]; then
    echo "QC (Mode : High)"
    qc_filt -h cg_filt.vcf.gz
    annovar_in="hq.vcf.gz"
    name="hq"
elif [[ "$mode" == "x" ]]; then
    echo "QC (Mode : Extra)"
    qc_filt -x cg_filt.vcf.gz
    annovar_in="xq.vcf.gz"
    name="xq"
else
    echo "Structural variant (Manta)"
    annovar_in="cg_filt.vcf.gz"
    name="sv"
fi

#Annovar
table_annovar.pl $annovar_in $db_path -buildver hg38 -out $name -remove -protocol refGene -operation g -nastring . -vcfinput

table_annovar.pl "$name".avinput $db_path -buildver hg38 -out hq.anno -remove -protocol refGeneWithVer,gnomad41_genome,dbnsfp42c,mcap,revel,icgc28,logofunc,intervar_20250721,clinvar_20250721 -operation g,f,f,f,f,f,f,f,f -nastring . -otherinfo -csvout -polish

table_annovar.pl cg_filt.vcf.gz $db_path -buildver hg38 -out pure -remove -protocol refGene -operation g -nastring . -vcfinput

table_annovar.pl pure.avinput $db_path -buildver hg38 -out pure.anno -remove -protocol refGeneWithVer,gnomad41_genome,dbnsfp42c,mcap,revel,icgc28,logofunc,intervar_20250721,clinvar_20250721 -operation g,f,f,f,f,f,f,f,f -nastring . -otherinfo -csvout -polish
